spring:
  profiles:
    active: dev
  application:
    name: api.admin.back
  servlet:
    multipart:
      max-file-size: 20MB
  devtools:
    livereload:
      enabled: true
      additional-paths: resources/**,static/**,templates/**
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
mybatis-plus:
  mapper-locations: classpath*:/com/module/**/*.xml
  check-config-location: true

logging:
  config: classpath:config/logback.xml

server:
  port: 8090
