spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.117:3306/base?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: root


upload:
  file:
    img: /home/work/upload/img
    video: /home/work/upload/video