spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.100.51:3306/base?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: base
    password: base

upload:
  file:
    base: D:/upload
    img: /img
    video: /video

logging:
  level:
    root: debug
  path: C:/logs/spring