spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/base?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: root


upload:
  file:
    base: /resource
    img: /uploadfile/img
    video: /uploadfile/video

logging:
  level:
    root: info
  path: /home/work/logs/spring