
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.17.156.180:3306/base?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: jinyun
    password: jinyun2019

upload:
  file:
    base: /resource
    img: /uploadfile/img
    video: /uploadfile/video

server:
  imgserver: https://www.jinyungold.cn/
  port: 8090

logging:
  level:
    root: info
  path: /home/work/logs/spring