spring:
  profiles:
    active: dev
  application:
    name: api.admin.back
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.117:3306/base?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: root
  devtools:
    livereload:
      enabled: true
      additional-paths: resources/**,static/**,templates/**
  servlet:
    multipart:
      max-file-size: 20MB
mybatis-plus:
  mapper-locations:  classpath*:/com/module/admin/back/mapper/**/*.xml
  check-config-location: true

