spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/base?useUnicode=true&useSSL=false&characterEncoding=utf8
    url: jdbc:mysql://localhost:3306/base?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: 11e4e0bb0d760f02


upload:
  file:
    base: /resource
    img: /uploadfile/img
    video: /uploadfile/video

server:
  imgserver: http://test.jinyungold.cn
  port: 9000

logging:
  level:
    root: info
  path: /home/work/logs/spring

unit:
  redis:
    address: redis://localhost:6379
    enable: true
  token:
    user_expired_days: 30
    visitor_expired_days: 7