spring:
  profiles:
    active: dev
  application:
    name: api.admin.back
  devtools:
    livereload:
      enabled: true
      additional-paths: resources/**,static/**,templates/**
  servlet:
    multipart:
      max-file-size: 20MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  mapper-locations:  classpath*:/com/module/**/*.xml
  check-config-location: true

logging:
  config: classpath:config/logback.xml
