
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.117:3306/base?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: base
    password: base

upload:
  file:
    img: D:/upload/img
    video: D:/upload/video


server:
  imgserver: http://192.168.1.80/

logging:
  level:
    root: info

unit:
  redis:
    address: redis://192.168.1.117:6379
    enable: true
  token:
    user_expired_days: 30
    visitor_expired_days: 7
