
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.17.156.180:3306/base?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: jinyun
    password: jinyun2019

upload:
  file:
    base: /resource
    img: /uploadfile/img
    video: /uploadfile/video

server:
  imgserver: https://www.jinyungold.cn/

logging:
  level:
    root: info
  path: /home/work/logs/spring

unit:
  redis:
    address: redis://192.168.1.117:6379
    enable: true
  token:
    user_expired_days: 30
    visitor_expired_days: 7