
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.100.23:3306/base?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: base
    password: base

upload:
  file:
    img: D:/upload/img
    video: D:/upload/video


server:
  imgserver: http://172.16.100.23/

logging:
  level:
    root: debug
  path: C:/logs/spring
unit:
  redis:
    address: redis://172.16.100.23:6379
    enable: true
  token:
    user_expired_days: 30
    visitor_expired_days: 7
