spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/base?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: 11e4e0bb0d760f02


logging:
  level:
    root: info
  path: /home/work/logs/spring