spring:
  profiles:
    active: dev
  application:
    name: api.admin.back

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  mapper-locations:  classpath*:/com/module/**/*.xml
  check-config-location: true

logging:
  config: classpath:config/logback.xml

